# This is a basic workflow to help you get started with Actions

name: "trigger-dynatrace-workflow"

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      trigger_dynatrace_workflow:
        description: Parameter used to decide if the Dynatrace workflow should be triggered
        type: boolean
        required: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: github-action-secrets
    name: Test custom action
    steps: 
      - name: Trigger Workflow
        if: inputs.trigger_dynatrace_workflow == true
        id: triggerDtWorkflow
        uses: danielp-dt/trigger-Dynatrace-workflows-action@v1.0.0
        with: 
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          tenant: 'vzx38435'
          endpoint: 'dev.apps.dynatracelabs.com'
          workflow_id: '3c9ef166-bae1-4c03-8b24-f19d32c9c42e'
          payload: |
            {
              "input": {
                "slack_message": "hello world via github",
                "new_issue_title": "some problem from github actions"
              },
              "params": {},
              "uniqueQualifier": ""
            }
      - name: Get response body
        run: |
          echo Output body ${{ steps.triggerDtWorkflow.outputs.response_body }}
